---
# Project information
site_name: eCOBIDAS
repo_name: Remi-Gau/eCobidas
repo_url: https://github.com/Remi-Gau/eCobidas
# docs_dir: alternative_path # docs/ is the default folder

# This will use Material them
theme:
    name: material
    language: en
    palette:
        primary: light blue
        accent: light blue

exclude_docs: |
    communication/README.md
    communication/abstracts/OHBM-2020-abstract.md
    communication/abstracts/OHBM-hackathon-2019-project-description.md
    methods_writing/README.md

# Pages
nav:
-   Welcome: index.md
-   Motivations: motivations.md
-   Goals:
    -   goals.md
    -   Short term goals: short-term.md
    -   Mid term goals: mid-term.md
    -   Long term goals: long-term.md
-   General organization: general-organization.md
-   Working with the spreadsheets: spreadsheets.md
-   Viewing the checklist: how-to-render-the-checklist.md
-   Apps: apps-table.md
-   Presets responses: preset-responses.md
-   How to contribute: how-to-contribute.md
-   Contributing: CONTRIBUTING.md
-   References: references.md

# list of extension
markdown_extensions:
-   admonition
-   pymdownx.details
