---
name: Test and coverage

# This workflow will install Python dependencies, run tests
# and lint with a variety of Python versions

# TODO
# - make sure the tests run online

# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

on: [push, pull_request]

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

        -   name: Clone repo
            uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.11

        -   name: Install dependencies
            run: |
                python -m pip install --upgrade pip setuptools
                pip install -r python/requirements.txt
                cd python && pip install -e . && cd ..
                mkdir -p lib && git clone https://github.com/Remi-Gau/reproschema-py.git lib/reproschema-py
                cd lib/reproschema-py && git checkout eCobidas_valid && pip install -e .

        -   name: Run tests and generate coverage report
            run: python -m pytest python/tests --cov=./ --cov-report=xml

        -   name: Upload coverage to Codecov
            uses: codecov/codecov-action@v4
            with:
                file: ./coverage.xml
                flags: unittests
                name: codecov-umbrella
                fail_ci_if_error: true
                verbose: true
