---
name: validate jsonld

on:
    push:
        branches:
        -   master
    pull_request:
        branches: '*'
    workflow_dispatch:

env:
    FORCE_COLOR: true

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
            with:
                submodules: true
        -   name: Setup Node
            uses: actions/setup-node@v4
            with:
                node-version: 12.x
        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: 3.11
        -   name: Install dependencies
            run: python -m pip install --upgrade pip tox
        -   name: Show tox config
            run: tox c
        -   name: Validate
            run: tox run -e validate_all
